services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_v2:/data/db

volumes:
    mongodb_data_v2: